<a href="https://colab.research.google.com/github/sanjeet123456789/python-deep-learning/blob/master/Basic_numpy_array_to_tensor__convergence.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import torch;
t1=torch.tensor(4.)
print(t1.dtype)
print(t1.shape)
print(t1)
t2=torch.tensor([1,2,3,4])
t3=torch.tensor([[5.,6],[7,8],[9,10]])
# Tensor Operations and gradients
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)
y=w*x+b
print(y)

torch.float32
torch.Size([])
tensor(4.)
tensor(17., grad_fn=<AddBackward0>)


In [11]:
#compute derivatives
y.backward()
print('dy/dx',x.grad)
print('dy/dw',w.grad)
print('dy/db',b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


In [0]:

import numpy as np #mutidimentional array
import matplotlib as mlt #for plotting and visualization
import pandas #for file I/O and data analysis

In [25]:
x=np.array([[9,6,4], [5,4,7], [2,4,5.]])
print(x)
#Convert the numpy to a torch tensor
y=torch.tensor(x)#create a copy of data
y=torch.from_numpy(x)#it doesnot create a copy
print(y)
print(x.dtype,y.dtype)

[[9. 6. 4.]
 [5. 4. 7.]
 [2. 4. 5.]]
tensor([[9., 6., 4.],
        [5., 4., 7.],
        [2., 4., 5.]], dtype=torch.float64)
float64 torch.float64


In [26]:
#Convert a torch tensor to a numpy array
z=y.numpy()
print(z)

[[9. 6. 4.]
 [5. 4. 7.]
 [2. 4. 5.]]
