<a href="https://colab.research.google.com/github/sanjeet123456789/python-deep-learning/blob/master/Linear_Regression_with_common_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import torch
from math import log
#Input temp,rainfall,humidity
inputs=np.array([[73,67,43],
                 [91,88,64],
                 [87,134,58],
                [102,43,37],
                 [69,96,70]],dtype='float32')

targets=np.array([[56,70],[81,101],
                 [119,133],
                  [22,37],
                  [103,119]
                  
                 ],dtype='float32')

In [2]:
#Convert inputand target into tensor
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [3]:
#Weights and biases
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-0.0828,  1.4440, -1.6088],
        [ 1.0154,  1.1747, -1.4349]], requires_grad=True)
tensor([0.3721, 0.7381], requires_grad=True)


In [0]:
#processing by multiplying data matrix with weights matrix and adding to the biase matrix
def model(x):
    return  x @ w.t() + b #@matrix represetion in pytorch


In [5]:
#Generating prediction
preds= model(inputs)
print(preds)

#Comparing with targets
print(targets)

tensor([[ 21.8986,  91.8712],
        [ 16.9476, 104.6856],
        [ 93.3564, 163.2711],
        [ -5.5054, 101.7343],
        [ 20.6679,  83.1347]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [0]:
#Loss function mse(mean square error)
def mse(t1,t2):
    diff=t1-t2
    return torch.sum(diff*diff)/diff.numel()#numel give number of element in diff

In [7]:
#Computing loss
loss=mse(preds,targets)
print(loss)

tensor(2034.3450, grad_fn=<DivBackward0>)


In [8]:
###########Compute Gradients
loss.backward()#required_grad must be true

#Gradients for weights
print(w)
print(w.grad)#for 2*3=6 weight getting the loss asociated with it
print(b)
print(b.grad)# for 2 baise find the grad associate with it


tensor([[-0.0828,  1.4440, -1.6088],
        [ 1.0154,  1.1747, -1.4349]], requires_grad=True)
tensor([[-3807.1270, -4088.8528, -2766.7981],
        [ 1738.7515,  1037.3065,   563.3314]])
tensor([0.3721, 0.7381], requires_grad=True)
tensor([-46.7270,  16.9394])


In [9]:
#If a gradient element is positive
#->increasing the element's value slightly will increase the loss
#->descresing the element's value slightly will descrease the loss

#If a grsdient element is negative
#->increasing the element's value slightly will descrease the loss
#->decresing the element's value slightly will increse the loss

#reseting the weight and baise grad with zero
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)
#Adjust the weight of gradient weight and baise
#generate Predictions
#Calculate the loss
#Compute gradient w.r.t. the weight and baises
#adjust the weightby subtractin a small quantity proportional to the gradients
# reset the gradient to zero


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [10]:


#Generate Prediction
preds=model(inputs)
print(preds)

#Calculate the loss
loss=mse(preds,targets)
print(loss)

#compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ 21.8986,  91.8712],
        [ 16.9476, 104.6856],
        [ 93.3564, 163.2711],
        [ -5.5054, 101.7343],
        [ 20.6679,  83.1347]], grad_fn=<AddBackward0>)
tensor(2034.3450, grad_fn=<DivBackward0>)
tensor([[-3807.1270, -4088.8528, -2766.7981],
        [ 1738.7515,  1037.3065,   563.3314]])
tensor([-46.7270,  16.9394])


In [11]:
from math import log
#Adjust weight &reset gradients
with torch.no_grad():
    w_ = w.grad * 1e-5
    b_ = b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

#print new weight
print(w)
print(b)

tensor([[-0.0828,  1.4440, -1.6088],
        [ 1.0154,  1.1747, -1.4349]], requires_grad=True)
tensor([0.3721, 0.7381], requires_grad=True)


In [12]:
#print new weight
print(w)
print(b)

#Calculate losss
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor([[-0.0828,  1.4440, -1.6088],
        [ 1.0154,  1.1747, -1.4349]], requires_grad=True)
tensor([0.3721, 0.7381], requires_grad=True)
tensor(2034.3450, grad_fn=<DivBackward0>)


In [0]:
#Train for multiple epochs
#train for 80 epochs
for i in range(80):
    preds=model(inputs)
    loss=mse(preds,targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [14]:
      
#calculate the loss
Preds =model(inputs)
loss=mse(preds,targets)

#Prediction
print(preds)
print(targets)

tensor([[ 59.1511,  76.7850],
        [ 67.2744,  87.8546],
        [149.4628, 151.6963],
        [ 30.6200,  72.2070],
        [ 70.4503,  76.4516]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
