<a href="https://colab.research.google.com/github/sanjeet123456789/python-deep-learning/blob/master/Linear_Regression_using_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Linear Regression using PyTorch
import torch.nn as nn
import torch
import numpy as np
#Inputs(temp,rainfall,humidity)
inputs=np.array([[75,89,45],[45,14,56],[78,89,63],
                [102,78,46],[99,88,77],[56,78,95],
                 [12,45,69],[96,75,15],[22,34,77],
                 [69,96,70],[73,67,43],[91,88,77],
                 [87,198,56],[103,68,77],[69,95,70.0]],dtype='float32')
#Targets(wheat,rice)
targets=np.array([[95,78],[66,77],[119,133],
                  [89,65],[98,78],[89,76],
                  [81,101],[119,133],[22,37],
                  [153,78],[56,70],[86,103],
                  [116,123],[56,42],[71,56]
                 ],dtype='float32')

inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)


In [11]:
#Dataset and DataLoader
from torch.utils.data import TensorDataset

#Define dataset
train_ds=TensorDataset(inputs,targets)
print(train_ds[0:3])
print(train_ds[[1,3,5,7]])


(tensor([[75., 89., 45.],
        [45., 14., 56.],
        [78., 89., 63.]]), tensor([[ 95.,  78.],
        [ 66.,  77.],
        [119., 133.]]))
(tensor([[ 45.,  14.,  56.],
        [102.,  78.,  46.],
        [ 56.,  78.,  95.],
        [ 96.,  75.,  15.]]), tensor([[ 66.,  77.],
        [ 89.,  65.],
        [ 89.,  76.],
        [119., 133.]]))


In [12]:
from torch.utils.data import DataLoader
# split data into batch of a predefined size
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)
for xb,yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[75., 89., 45.],
        [96., 75., 15.],
        [69., 96., 70.],
        [45., 14., 56.],
        [12., 45., 69.]])
tensor([[ 95.,  78.],
        [119., 133.],
        [153.,  78.],
        [ 66.,  77.],
        [ 81., 101.]])


In [16]:
   
#define model
model=nn.Linear(3,2)# 3 input and 2 output
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.1105, -0.5336, -0.3855],
        [-0.2759, -0.3758, -0.4982]], requires_grad=True)
Parameter containing:
tensor([0.3946, 0.1253], requires_grad=True)


In [17]:
#parameters return list of all baise and weights
list(model.parameters())


[Parameter containing:
 tensor([[-0.1105, -0.5336, -0.3855],
         [-0.2759, -0.3758, -0.4982]], requires_grad=True),
 Parameter containing:
 tensor([0.3946, 0.1253], requires_grad=True)]

In [19]:
preds=model(inputs)
print(preds)
print(targets)

tensor([[ -72.7246,  -76.4289],
        [ -33.6341,  -45.4482],
        [ -79.9949,  -86.2234],
        [ -70.2239,  -80.2433],
        [ -87.1782,  -98.6160],
        [ -84.0310,  -91.9605],
        [ -51.5399,  -54.4678],
        [ -56.0101,  -62.0179],
        [ -49.8595,  -57.0787],
        [ -85.4339,  -89.8576],
        [ -59.9945,  -66.6138],
        [ -86.2944,  -96.4086],
        [-136.4481, -126.1786],
        [ -76.9490,  -92.2042],
        [ -84.9003,  -89.4818]], grad_fn=<AddmmBackward>)
tensor([[ 95.,  78.],
        [ 66.,  77.],
        [119., 133.],
        [ 89.,  65.],
        [ 98.,  78.],
        [ 89.,  76.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [153.,  78.],
        [ 56.,  70.],
        [ 86., 103.],
        [116., 123.],
        [ 56.,  42.],
        [ 71.,  56.]])


In [20]:
#loss function
import torch.nn.functional as F
loss_fn=F.mse_loss
loss=loss_fn(model(inputs),targets)
print(loss)

tensor(28420.7617, grad_fn=<MseLossBackward>)


In [0]:
#optimizer
#define optimizer stochastic gradient desent
opt=torch.optim.SGD(model.parameters(),lr=1e-5)
#adam
#rmsprop

In [0]:
#train the model
def fit(num_epochs,model,loss_fn,opt):
    #repeat for given number of epochs
    for epoch in range(num_epochs):
        #train with batch of data
        for xb,yb in train_dl:
            #Generating  prediction
            pred=model(xb)
            # Calculate loss
            loss=loss_fn(pred,yb)
            #compute gradients
            loss.backward()
            #update parameters using gradients
            opt.step()
            #Reset the gradient to zero
            opt.zero_grad()
        #print progress
        if(epoch+1)%10==0:
            print('Epochs[{}/{}],Loss:{:.4f}'.format(epoch+1,num_epochs,loss.item()))

In [28]:
#train the model
fit(400,model,loss_fn,opt)

Epochs[10/400],Loss:382.1761
Epochs[20/400],Loss:1392.2644
Epochs[30/400],Loss:1257.5901
Epochs[40/400],Loss:1048.1176
Epochs[50/400],Loss:818.0488
Epochs[60/400],Loss:566.2281
Epochs[70/400],Loss:1078.5481
Epochs[80/400],Loss:459.3264
Epochs[90/400],Loss:852.1952
Epochs[100/400],Loss:996.8306
Epochs[110/400],Loss:258.1724
Epochs[120/400],Loss:1667.9125
Epochs[130/400],Loss:982.8255
Epochs[140/400],Loss:1620.2378
Epochs[150/400],Loss:851.5975
Epochs[160/400],Loss:1410.6937
Epochs[170/400],Loss:798.7283
Epochs[180/400],Loss:1401.5544
Epochs[190/400],Loss:305.5558
Epochs[200/400],Loss:1172.5072
Epochs[210/400],Loss:1138.5754
Epochs[220/400],Loss:1178.1365
Epochs[230/400],Loss:670.7391
Epochs[240/400],Loss:874.9301
Epochs[250/400],Loss:1085.6090
Epochs[260/400],Loss:176.7318
Epochs[270/400],Loss:759.7612
Epochs[280/400],Loss:1174.4287
Epochs[290/400],Loss:849.4178
Epochs[300/400],Loss:1481.1278
Epochs[310/400],Loss:832.5601
Epochs[320/400],Loss:1137.4470
Epochs[330/400],Loss:362.0429
Epoc

In [29]:
#Generate Predictions
preds=model(inputs)
print(preds)

#Compare with targets
print(targets)

tensor([[ 84.6581,  77.3566],
        [ 43.2102,  39.2053],
        [ 91.4277,  83.8663],
        [ 92.2809,  82.9892],
        [104.5285,  95.3067],
        [ 86.7529,  81.0226],
        [ 45.5687,  43.7561],
        [ 78.9934,  70.2527],
        [ 47.7895,  45.3174],
        [ 92.5045,  85.5549],
        [ 73.9271,  67.0635],
        [100.9904,  92.3990],
        [139.0803, 129.4426],
        [ 97.8960,  88.6115],
        [ 92.0844,  85.1474]], grad_fn=<AddmmBackward>)
tensor([[ 95.,  78.],
        [ 66.,  77.],
        [119., 133.],
        [ 89.,  65.],
        [ 98.,  78.],
        [ 89.,  76.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [153.,  78.],
        [ 56.,  70.],
        [ 86., 103.],
        [116., 123.],
        [ 56.,  42.],
        [ 71.,  56.]])
