<a href="https://colab.research.google.com/github/sanjeet123456789/python-deep-learning/blob/master/Linear_Regression_with_common_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import torch
from math import log
#Input temp,rainfall,humidity
inputs=np.array([[73,67,43],
                 [91,88,64],
                 [87,134,58],
                [102,43,37],
                 [69,96,70]],dtype='float32')

targets=np.array([[56,70],[81,101],
                 [119,133],
                  [22,37],
                  [103,119]
                  
                 ],dtype='float32')

In [28]:
#Convert inputand target into tensor
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [29]:
#Weights and biases
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-1.9227, -1.4288,  0.5809],
        [-0.0312,  0.6042, -0.1182]], requires_grad=True)
tensor([-0.6862, -0.1524], requires_grad=True)


In [0]:
#processing by multiplying data matrix with weights matrix and adding to the biase matrix
def model(x):
    return  x @ w.t() + b #@matrix represetion in pytorch


In [31]:
#Generating prediction
preds= model(inputs)
print(preds)

#Comparing with targets
print(targets)

tensor([[-211.7916,   32.9676],
        [-264.2052,   42.6114],
        [-325.7265,   71.2405],
        [-236.7422,   18.2701],
        [-229.8518,   47.4226]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [0]:
#Loss function mse(mean square error)
def mse(t1,t2):
    diff=t1-t2
    return torch.sum(diff*diff)/diff.numel()#numel give number of element in diff

In [33]:
#Computing loss
loss=mse(preds,targets)
print(loss)

tensor(58046.7500, grad_fn=<DivBackward0>)


In [34]:
###########Compute Gradients
loss.backward()#required_grad must be true

#Gradients for weights
print(w)
print(w.grad)#for 2*3=6 weight getting the loss asociated with it
print(b)
print(b.grad)# for 2 baise find the grad associate with it


tensor([[-1.9227, -1.4288,  0.5809],
        [-0.0312,  0.6042, -0.1182]], requires_grad=True)
tensor([[-27802.4297, -30198.6289, -18455.0801],
        [ -4047.8208,  -4714.3936,  -2922.9490]])
tensor([-0.6862, -0.1524], requires_grad=True)
tensor([-329.8635,  -49.4976])


In [35]:
#If a gradient element is positive
#->increasing the element's value slightly will increase the loss
#->descresing the element's value slightly will descrease the loss

#If a grsdient element is negative
#->increasing the element's value slightly will descrease the loss
#->decresing the element's value slightly will increse the loss

#reseting the weight and baise grad with zero
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)
#Adjust the weight of gradient weight and baise
#generate Predictions
#Calculate the loss
#Compute gradient w.r.t. the weight and baises
#adjust the weightby subtractin a small quantity proportional to the gradients
# reset the gradient to zero


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [36]:


#Generate Prediction
preds=model(inputs)
print(preds)

#Calculate the loss
loss=mse(preds,targets)
print(loss)

#compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-211.7916,   32.9676],
        [-264.2052,   42.6114],
        [-325.7265,   71.2405],
        [-236.7422,   18.2701],
        [-229.8518,   47.4226]], grad_fn=<AddBackward0>)
tensor(58046.7500, grad_fn=<DivBackward0>)
tensor([[-27802.4297, -30198.6289, -18455.0801],
        [ -4047.8208,  -4714.3936,  -2922.9490]])
tensor([-329.8635,  -49.4976])


In [42]:
from math import log
#Adjust weight &reset gradients
with torch.no_grad():
    w_ = w.grad * le-5
    b_ = b.grad * le-5
    w.grad.zero_()
    b.grad.zero_()

#print new weight
print(w)
print(b)

NameError: ignored

In [0]:

#print new weight
print(w)
print(b)

#Calculate losss
preds=model(inputs)
loss=mseo(preds,targets)
print(loss)


#Train for multiple epochs
#train for 80 epochs
for i in range(80):
    preds=model(inputs)
    loss=mse(preds,targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * le-5
        b -= b.grad * le-5
        w.grad.zero_()
        b.grad.zero_()
        
#calculate the loss
Preds =model(inputs)
loss=mse(preds,targets)

#Prediction
print(preds)
print(targets)